### ISSUE TITLE
well done Sagor, Keep up the hardwork

### ISSUE THREAD

**Issue by AdnanAfsari** [sagor9116/PHOENIX-#1]
- [x]  Fix this navigation responsive issue
Note:: I loved the way you used variables in styles.

<img width="702" alt="Screenshot 2021-07-28 at 7 01 39 PM" src="https://user-images.githubusercontent.com/8613710/127327671-13d0c97d-482d-4cae-973b-b9317cfc624e.png">

**Comment by AdnanAfsari** [comment]
@sagor9116

**Comment by sagor9116** [comment]
Thank you @AdnanAfsari :) :) . I will fix the issue as soon as possible.

**Comment by sagor9116** [comment]
I have fixed the issue. 
https://modest-wing-80d1ca.netlify.app/

**Comment by AdnanAfsari** [comment]
Well done 👍 . Looks good
